#ifndef APIMONITOR_VERSION_H
#define APIMONITOR_VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 6
#define APP_VERSION_BUILD 0

#define APP_DISPLAY_NAME_STRING "API Monitor"
#define APP_DISPLAY_NAME_WSTRING L"API Monitor"

#define APP_VERSION_RESOURCE 1,0,6,0
#define APP_VERSION_STRING "1.0.6"
#define APP_FILE_VERSION_STRING "1.0.6.0"
#define APP_VERSION_WSTRING L"1.0.6"

#endif
